/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypack;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author Jarvis
 */
public class Pallete extends javax.swing.JFrame {

    /**
     * Creates new form Pallete
     */
    public Pallete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setText("Vote");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setText("ABVP");

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel4.setText("AISU");

        jButton2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton2.setText("Vote");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setText("CPIS");

        jButton3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton3.setText("Vote");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("SFI");

        jButton4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton4.setText("Vote");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel9.setText("Vote for the best you see");

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel10.setText("Enter ID");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel10)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 300);

        setSize(new java.awt.Dimension(400, 301));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            
            User_p u=new User_p();
            String s=jTextField1.getText();
            String k="yes";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            Statement stmt=con2.createStatement();
            ResultSet rs=stmt.executeQuery("select * from voters");
             int c=0;
            while(rs.next())
            
            {  String user = rs.getString(1);
            if(s.equals(user))
            {
            
            
            if(s.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Please enter your proper ID. ");
            System.exit(0);
            }
            else
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst=con.prepareStatement("update parties set votes=votes+1 where p_name='ABVP'");
            //pst.setString(1, nm);
            //pst.setString(2, mob);
            //pst.setString(3, id);
           // pst.setString(4, gen);
            //pst.setString(5, vt);
            int status=pst.executeUpdate();   
            if(status>0)
            {
            JOptionPane.showMessageDialog(rootPane, "Updated successfly: ");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst1=con1.prepareStatement("update voters set voted='"+k+"' where id='"+s+"'");
            //JOptionPane.showMessageDialog(rootPane, "Thank You for casting your vote");
            
            int status1=pst1.executeUpdate();
           
            if(status1>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Voted successfully");
                User_p w=new User_p();
                 w.setVisible(true);
                 this.dispose();
                 c++;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            
            }}}
            if(c==0)
            {
                 JOptionPane.showMessageDialog(rootPane, "invalid voter");
                 System.exit(0);
                 
            }
        }
            
            catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      try{  
          User_p u=new User_p();
            String s=jTextField1.getText();
            String k="yes";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            Statement stmt=con2.createStatement();
            ResultSet rs=stmt.executeQuery("select * from voters");
             int c=0;
            while(rs.next())
            
            {  String user = rs.getString(1);
            if(s.equals(user))
            {
            
            
            if(s.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Please enter your proper ID. ");
            System.exit(0);
            }
            else
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst=con.prepareStatement("update parties set votes=votes+1 where p_name='AISU'");
            //pst.setString(1, nm);
            //pst.setString(2, mob);
            //pst.setString(3, id);
           // pst.setString(4, gen);
            //pst.setString(5, vt);
            int status=pst.executeUpdate();   
            if(status>0)
            {
            JOptionPane.showMessageDialog(rootPane, "Updated successfly: ");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst1=con1.prepareStatement("update voters set voted='"+k+"' where id='"+s+"'");
            //JOptionPane.showMessageDialog(rootPane, "Thank You for casting your vote");
            
            int status1=pst1.executeUpdate();
           
            if(status1>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Voted successfully");
                User_p w=new User_p();
                 w.setVisible(true);
                 this.dispose();
                 c++;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            }}
            if(c==0)
            {
                 JOptionPane.showMessageDialog(rootPane, "invalid voter");
                 System.exit(0);
                 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try{
            
            User_p u=new User_p();
            String s=jTextField1.getText();
            String k="yes";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            Statement stmt=con2.createStatement();
            ResultSet rs=stmt.executeQuery("select * from voters");
             int c=0;
            while(rs.next())
            
            {  String user = rs.getString(1);
            if(s.equals(user))
            {
            
            
            if(s.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Please enter your proper ID. ");
            System.exit(0);
            }
            else
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst=con.prepareStatement("update parties set votes=votes+1 where p_name='CPIS'");
            //pst.setString(1, nm);
            //pst.setString(2, mob);
            //pst.setString(3, id);
           // pst.setString(4, gen);
            //pst.setString(5, vt);
            int status=pst.executeUpdate();   
            if(status>0)
            {
            JOptionPane.showMessageDialog(rootPane, "Updated successfly: ");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst1=con1.prepareStatement("update voters set voted='"+k+"' where id='"+s+"'");
            //JOptionPane.showMessageDialog(rootPane, "Thank You for casting your vote");
            
            int status1=pst1.executeUpdate();
           
            if(status1>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Voted successfully");
                User_p w=new User_p();
                 w.setVisible(true);
                 this.dispose();
                 c++;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            }}
            if(c==0)
            {
                 JOptionPane.showMessageDialog(rootPane, "invalid voter");
                 System.exit(0);
                 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
            User_p u=new User_p();
            String s=jTextField1.getText();
            String k="yes";
            Class.forName("com.mysql.jdbc.Driver");
            Connection con2=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            Statement stmt=con2.createStatement();
            ResultSet rs=stmt.executeQuery("select * from voters");
             int c=0;
            while(rs.next())
            
            {  String user = rs.getString(1);
            if(s.equals(user))
            {
            
            
            if(s.equals(""))
            {
            JOptionPane.showMessageDialog(rootPane, "Please enter your proper ID. ");
            System.exit(0);
            }
            else
            {
             Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst=con.prepareStatement("update parties set votes=votes+1 where p_name='SFI'");
            //pst.setString(1, nm);
            //pst.setString(2, mob);
            //pst.setString(3, id);
           // pst.setString(4, gen);
            //pst.setString(5, vt);
            int status=pst.executeUpdate();   
            if(status>0)
            {
            JOptionPane.showMessageDialog(rootPane, "Updated successfly: ");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con1=DriverManager.getConnection("jdbc:mysql://localhost:3307/voting", "root", "password");
            PreparedStatement pst1=con1.prepareStatement("update voters set voted='"+k+"' where id='"+s+"'");
            //JOptionPane.showMessageDialog(rootPane, "Thank You for casting your vote");
            
            int status1=pst1.executeUpdate();
           
            if(status1>0)
            {
                JOptionPane.showMessageDialog(rootPane, "Voted successfully");
                User_p w=new User_p();
                 w.setVisible(true);
                 this.dispose();
                 c++;
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            else
            {
                JOptionPane.showMessageDialog(rootPane, "Data not inserted:");
                System.exit(0);
            }
            }
            }}
            if(c==0)
            {
                 JOptionPane.showMessageDialog(rootPane, "invalid voter");
                 System.exit(0);
                 
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pallete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pallete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pallete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pallete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pallete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    void sets1(String s1) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
